#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from mavros_msgs.srv import *
from std_msgs.msg import String
import rospy

if __name__ == '__main__':
    rospy.init_node('tezos_turtle')

    set_mode = rospy.ServiceProxy('/mavros/set_mode', SetMode)
    arming = rospy.ServiceProxy('/mavros/cmd/arming', CommandBool)

    def liability(msg):
        rospy.loginfo('My liability %s, launch drone...', msg.data)
        #
        set_mode(0, 'ALT_HOLD')
        rospy.sleep(2)
        arming(True)
        rospy.sleep(5)
        set_mode(0, 'AUTO')

    rospy.Subscriber('/liability/incoming', String, liability)
    rospy.spin()
